WIP

diff --git a/.github/workflows/l2-cache-ci.yml b/.github/workflows/l2-cache-ci.yml
--- a/.github/workflows/l2-cache-ci.yml
+++ b/.github/workflows/l2-cache-ci.yml
@@ -96,6 +96,200 @@ jobs:
           name: patmos-tools
           path: artifacts
 
+  tacle-bench-test:
+    runs-on: ubuntu-latest
+    needs: [ build-tools ]
+
+    steps:
+      - name: Download tools
+        uses: actions/download-artifact@v4
+        with:
+          name: patmos-tools
+
+      - name: Add toolchain to PATH
+        run: echo "$PWD/artifacts/bin" >> $GITHUB_PATH
+
+      - name: Checkout TACLe benchmark repository
+        uses: actions/checkout@v3
+        with:
+          repository: tacle/tacle-bench
+          path: tacle
+
+      - name: Verify patmos-clang
+        run: patmos-clang --version
+
+      - name: Verify emulator
+        run: patemu -h
+
+      - name: Run TACLe benchmarks
+        working-directory: tacle/bench
+        run: |
+          set +e
+
+          COMPILER=patmos-clang
+          COMPILER_OPTIONS=" -Wall -Wno-unknown-pragmas -Werror -O2"
+          EXEC=patemu
+          PASS=0
+          FAIL_COMP=0
+          FAIL_EXEC=0
+
+          for dir in */ ; do
+              # Skip the 'parallel' directory entirely
+              [[ "$dir" == "parallel/" ]] && continue
+
+              printf "Entering ${dir}\n"
+              cd "$dir"
+
+              for BENCH in */ ; do
+                  # Skip benchmarks that do not compile or not work properly
+                  case "$dir$BENCH" in
+                      "kernel/pm/"| \
+                      "kernel/isqrt/"| \
+                      "sequential/rijndael_dec/"| \
+                      "sequential/rijndael_enc/")
+                          echo "Skipping ${dir}${BENCH}"
+                          continue
+                          ;;
+                  esac
+
+                  printf "Checking ${dir}${BENCH}\n"
+                  cd "$BENCH"
+
+                  if [ -f a.out ]; then
+                      rm a.out
+                  fi
+
+                  if [ -f *.o ]; then
+                      rm *.o
+                  fi
+
+                  $COMPILER $COMPILER_OPTIONS *.c
+
+                  if [ -f a.out ]; then
+                      $EXEC ./a.out
+                      RETURNVALUE=$(echo $?)
+                      if [ $RETURNVALUE -eq 0 ]; then
+                          printf "passed. \n"
+                          ((PASS++))
+                      else
+                          printf "failed (wrong return value $RETURNVALUE). \n"
+                          ((FAIL_EXEC++))
+                      fi
+                  else
+                    printf "failed (compiled with errors/warnings). \n"
+                    ((FAIL_COMP++))
+                  fi
+
+                  cd ..
+              done
+
+              printf "Leaving ${dir}\n\n"
+              cd ..
+          done
+
+          echo "PASS: $PASS, FAIL_COMP: $FAIL_COMP, FAIL_EXEC: $FAIL_EXEC"
+
+          if [ "$FAIL_EXEC" -gt 0 ]; then
+              exit 1
+          fi
+          
+          tacle-bench-test:
+            runs-on: ubuntu-latest
+            needs: [ build-tools ]
+
+            steps:
+              - name: Download tools
+                uses: actions/download-artifact@v4
+                with:
+                  name: patmos-tools
+
+              - name: Add toolchain to PATH
+                run: echo "$PWD/artifacts/bin" >> $GITHUB_PATH
+
+              - name: Checkout TACLe benchmark repository
+                uses: actions/checkout@v3
+                with:
+                  repository: tacle/tacle-bench
+                  path: tacle
+
+              - name: Verify patmos-clang
+                run: patmos-clang --version
+
+              - name: Verify emulator
+                run: patemu -h
+
+              - name: Run TACLe benchmarks
+                working-directory: tacle/bench
+                run: |
+                  set +e
+
+                  COMPILER=patmos-clang
+                  COMPILER_OPTIONS=" -Wall -Wno-unknown-pragmas -Werror -O2"
+                  EXEC=patemu
+                  PASS=0
+                  FAIL_COMP=0
+                  FAIL_EXEC=0
+
+                  for dir in */ ; do
+                      # Skip the 'parallel' directory entirely
+                      [[ "$dir" == "parallel/" ]] && continue
+
+                      printf "Entering ${dir}\n"
+                      cd "$dir"
+
+                      for BENCH in */ ; do
+                          # Skip benchmarks that do not compile or not work properly
+                          case "$dir$BENCH" in
+                              "kernel/pm/"| \
+                              "kernel/isqrt/"| \
+                              "sequential/rijndael_dec/"| \
+                              "sequential/rijndael_enc/")
+                                  echo "Skipping ${dir}${BENCH}"
+                                  continue
+                                  ;;
+                          esac
+
+                          printf "Checking ${dir}${BENCH}\n"
+                          cd "$BENCH"
+
+                          if [ -f a.out ]; then
+                              rm a.out
+                          fi
+
+                          if [ -f *.o ]; then
+                              rm *.o
+                          fi
+
+                          $COMPILER $COMPILER_OPTIONS *.c
+
+                          if [ -f a.out ]; then
+                              $EXEC ./a.out
+                              RETURNVALUE=$(echo $?)
+                              if [ $RETURNVALUE -eq 0 ]; then
+                                  printf "passed. \n"
+                                  ((PASS++))
+                              else
+                                  printf "failed (wrong return value $RETURNVALUE). \n"
+                                  ((FAIL_EXEC++))
+                              fi
+                          else
+                            printf "failed (compiled with errors/warnings). \n"
+                            ((FAIL_COMP++))
+                          fi
+
+                          cd ..
+                      done
+
+                      printf "Leaving ${dir}\n\n"
+                      cd ..
+                  done
+
+                  echo "PASS: $PASS, FAIL_COMP: $FAIL_COMP, FAIL_EXEC: $FAIL_EXEC"
+
+                  if [ "$FAIL_EXEC" -gt 0 ]; then
+                      exit 1
+                  fi
+
   patmos-bench-test:
     runs-on: ubuntu-latest
     needs: [ build-tools ]
@@ -109,18 +303,11 @@ jobs:
       - name: Add toolchain to PATH
         run: echo "$PWD/artifacts/bin" >> $GITHUB_PATH
 
-#      - name: Checkout TACLe benchmark repository
-#        uses: actions/checkout@v3
-#        with:
-#          repository: tacle/tacle-bench
-#          path: tacle
-#
-#      - name: Verify patmos-clang
-#        run: patmos-clang --version
-#
-#      - name: Verify emulator
-#        run: patemu -h
-#
-#      - name: Run TACLe benchmarks
-#        working-directory: tacle/bench
-#        run:
+      - name: Verify patmos-clang
+        run: patmos-clang --version
+
+      - name: Verify emulator
+        run: patemu -h
+
+      - name: Patmos benchmarks
+        run: echo "\n"
